import { FormData, ReportData } from '../types';

export const defaultFormData: FormData = {
  // Page 1 - Request Information
  isPart: false,
  isMaterial: false,
  materialCode: '',
  partMaterial: '',
  supplierCode: '',
  supplierName: '',
  shippedCargoType: '',
  isPrelaunch: false,
  isPrototype: false,
  site: '',
  dateSentToFactory: '',
  billOfLadingNo: '',
  quantity: '',
  reasonMaterialChange: false,
  reasonApprovalExpiry: false,
  reasonNewSupplier: false,
  reasonChangeDesign: false,
  reasonNewPart: false,
  reasonProcessChange: false,
  productTechnicalCode: '',
  productName: '',
  productStage: '',
  isMassProduction: false,
  isProductDevelopment: false,
  dataSheetNo: '',
  drawingNo: '',
  manufacturerSelectionNumber: '',
  requesterName: '',
  requesterPosition: '',
  requesterDateSignature: '',
  approverName: '',
  approverPosition: '',
  approverDateSignature: '',
  
  // Page 2 - Initial Review
  requestAcceptable: false,
  notAcceptable: false,
  notAcceptableDueTo: '',
  qaName1: '',
  qaPosition1: '',
  qaDateSignature1: '',
  noTestReport: false,
  noECR: false,
  qaName2: '',
  qaPosition2: '',
  qaDateSignature2: '',
  noSample: false,
  noPrototype: false,
  
  // Page 3 - Review Process
  dimensionalOK: false,
  dimensionalNOK: false,
  dimensionalEvidence: '',
  materialOK: false,
  materialNOK: false,
  materialEvidence: '',
  durabilityOK: false,
  durabilityNOK: false,
  durabilityEvidence: '',
  performanceOK: false,
  performanceNOK: false,
  performanceEvidence: '',
  assemblyOK: false,
  assemblyNOK: false,
  assemblyEvidence: '',
  documentsOK: false,
  documentsNOK: false,
  documentsEvidence: '',
  samplesOK: false,
  samplesNOK: false,
  samplesEvidence: '',
  betterThan: false,
  worseThan: false,
  sameAs: false,
  noParallel: false,
  comparisonEvidence: '',
  expertName1: '',
  expertPosition1: '',
  expertDateSignature1: '',
  managerName1: '',
  managerPosition1: '',
  managerDateSignature1: '',
  isGeneral: true,
  isExclusive: false,
  documentCode: '',
  
  // Page 4 - Additional fields
  durabilityOKP4: false,
  durabilityNOKP4: false,
  durabilityEvidenceP4: '',
  performanceOKP4: false,
  performanceNOKP4: false,
  performanceEvidenceP4: '',
  assemblyOKP4: false,
  assemblyNOKP4: false,
  assemblyEvidenceP4: '',
  documentsOKP4: false,
  documentsNOKP4: false,
  documentsEvidenceP4: '',
  samplesOKP4: false,
  samplesNOKP4: false,
  samplesEvidenceP4: '',
  betterThanP4: false,
  worseThanP4: false,
  sameAsP4: false,
  noParallelP4: false,
  comparisonEvidenceP4: '',
  expertName2: '',
  expertPosition2: '',
  expertDateSignature2: '',
  managerName2: '',
  managerPosition2: '',
  managerDateSignature2: '',
  
  // Page 5 - QA and Management
  qaExpertName: '',
  qaExpertPosition: '',
  qaExpertDateSignature: '',
  qaManagerName: '',
  qaManagerPosition: '',
  qaManagerDateSignature: '',
  isApproved: false,
  isConditionallyApproved: false,
  isApprovedLimited: false,
  isRejected: false,
  approvalDescription: '',
  approvalUntilDate: '',
  deputyName: '',
  deputyPosition: '',
  deputyDateSignature: '',
  prelaunchNeeded: false,
  prelaunchNotNeeded: false,
  auditNeeded: false,
  auditNotNeeded: false,
  
  // Page 6 - Final Registration
  archiveDate: '',
  evidence: '',
  actions: '',
  finalName: '',
  finalPosition: '',
  finalDateSignature: '',
  isGeneralP6: true,
  isExclusiveP6: false,
  documentCodeP6: ''
};

export const initialReportsData: ReportData[] = [];